version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  bdd:
    image: phuocleautoqa/selenium-docker-bdd
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - CUCUMBER_OPTIONS=classpath:features --tags @selenium-docker
    volumes:
      - ./output:/usr/share/udemy/target/cucumber-reports